AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Stack for example Serverless API
Globals:
  Function:
    Timeout: 10
Resources:
  InsertTodoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: todo/
      Handler: insert.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        ApiGatewayEvent:
          Type: Api
          Properties:
            Path: /
            Method: post
      Role: !GetAtt LambdaSQSRole.Arn
      Environment:
        Variables:
          TODO_TABLE_NAME: !Sub "${DynamoDBTodoTable}"
          EMAIL_QUEUE_URL: !GetAtt EmailQueue.QueueUrl
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - insert.ts
  DeleteTodoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: todo/
      Handler: delete.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        ApiGatewayEvent:
          Type: Api
          Properties:
            Path: /{id}
            Method: delete
      Role: !GetAtt LambdaSQSRole.Arn
      Environment:
        Variables:
          TODO_TABLE_NAME: !Sub "${DynamoDBTodoTable}"
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - delete.ts
    DependsOn:
      - DynamoDBTodoTable
      - EmailQueue
  DynamoDBTodoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 3
        WriteCapacityUnits: 3
  EmailQueue:
    Type: "AWS::SQS::Queue"
    Properties:
      QueueName: !Sub ${AWS::StackName}-email-queue
  LambdaSQSRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: MyLambdaPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                  - sqs:GetQueueUrl
                Resource: !GetAtt EmailQueue.Arn
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                Resource: !GetAtt DynamoDBTodoTable.Arn
Outputs:
  InsertTodoFunction:
    Description: Insert Todo Lambda Function ARN
    Value: !GetAtt InsertTodoFunction.Arn
  DynamoDBTodoTableName:
    Value: !Ref DynamoDBTodoTable
  EmailQueueArn:
    Value: !GetAtt EmailQueue.Arn
    Description: "ARN of the EmailQueue"
  EmailQueueUrl:
    Value: !GetAtt EmailQueue.QueueUrl
    Description: "URL of the EmailQueue"
