AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Stack for example Serverless API to send mails
Globals:
  Function:
    Timeout: 3
Resources:
  InsertTodoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: todo/
      Handler: insert.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        ApiGatewayEvent:
          Type: Api
          Properties:
            Path: /insert
            Method: post
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - insert.ts
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: partitionKey
          AttributeType: S
        - AttributeName: sortKey
          AttributeType: N
      KeySchema:
        - AttributeName: partitionKey
          KeyType: HASH
        - AttributeName: sortKey
          KeyType: RANGE
      TableName: TodoTable
Outputs:
  InsertTodoFunction:
    Description: Insert Todo Lambda Function ARN
    Value: !GetAtt InsertTodoFunction.Arn
